apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/cert-manager.yaml
  - apps/metrics-server.yaml
  - apps/aws-load-balancer-controller.yaml
  - apps/external-secrets.yaml
  - apps/kyverno.yaml
  - apps/trivy-operator.yaml
  - apps/reloader.yaml
  - apps/karpenter.yaml
  - apps/karpenter-manifests-application.yaml
  - apps/prometheus.yaml
  - apps/loki.yaml
  - apps/microservices-apps-deploy.yaml
