apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform-addons
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.2
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: __EKS_CLUSTER_NAME__
        region: __AWS_REGION__
        vpcId: __VPC_ID__
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: __AWS_LOAD_BALANCER_CONTROLLER_ROLE_ARN__
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

